# Generated by Django 4.0.6 on 2022-07-04 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('run', 'Запущен'), ('stopped', 'Остновлен')], default='created', max_length=20, verbose_name='Статус')),
                ('creation_time', models.TimeField(auto_now_add=True, verbose_name='Время создания')),
                ('list_of_performers', models.CharField(max_length=20, validators=[django.core.validators.int_list_validator], verbose_name='Список исполнителей')),
            ],
            options={
                'ordering': ['-priority', 'creation_time'],
            },
        ),
    ]
